### ISSUE TITLE
allow to specify udp + tcp port for server

### ISSUE THREAD

**Issue by abma** [spring/SpringLS#1]
these values are currently hard-coded:

https://github.com/spring/TASServer/blob/master/src/main/java/com/springrts/tasserver/Server.java#L58
https://github.com/spring/TASServer/blob/master/src/main/java/com/springrts/tasserver/NatHelpServer.java#L33

replace with config-values

**Comment by hoijui** [comment]
It is possible to set both of these through cmd-line args:
-  -p,--port <port-number>
  The main (TCP) port number to host on [1, 65535].  The default is 8200.
- -n,--nat-port <NAT-port-number>
  The (UDP) port number to host the NAT traversal techniques help service on
  [1, 65535], which lets clients detect their source port, for example when
  using "hole punching". The default is 8201.

not sure when this was added, might have been b32f826913500f5272ac237298e8d1f0179fd93b
